### ISSUE TITLE
OTF

### ISSUE THREAD

**Issue by Logic-gate** [casalinovalerio/scripts#1]
Hey,

First of all cheers for using otf, I like seeing a pastime project of mine garnering a bit of momentum. 

I don't know if you know this, but otf supports user validated uploads through keybase. The docs are here if you're interested. https://logic-gate-demo.readthedocs.io/en/latest/usage.html

Cheers again for the support, much appreciated.

**Comment by casalinovalerio** [comment]
Hey,

Thanks! I wasn't aware of the documentation, this makes everything easier.

Your APIs are very useful and easy to use, even if it is a pastime project it is perfectly made, cheers to you!

**Comment by Logic-gate** [comment]
Cheers,

If you need any assistance, let me know. 

And thanks again.

**Comment by casalinovalerio** [comment]
You might wanna take a look to https://github.com/casalinovalerio/kitc

OTF is full implemented in that one ;)

**Comment by Logic-gate** [comment]
Cheers, lgtm. Will start using it. 👍
